service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: debug

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: trace_storage
      traces_archive:
      metrics: metrics_storage
    base_path: /
    ui:
      config_file: /etc/jaeger/config-ui.json
      log_access: true
    grpc:
      endpoint: 0.0.0.0:16685
    http:
      endpoint: 0.0.0.0:16686

  jaeger_storage:
    backends:
      trace_storage:
        elasticsearch:
          server_urls:
            - http://elasticsearch:9200
          indices:
            index_prefix: "jaeger-main"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "week"
              shards: 1
              replicas: 0
            services:
              date_layout: "2006-01-02"
              rollover_frequency: "week"
              shards: 1
              replicas: 0
            dependencies:
              date_layout: "2006-01-02"
              rollover_frequency: "week"
              shards: 1
              replicas: 0
            sampling:
              date_layout: "2006-01-02"
              rollover_frequency: "week"
              shards: 1
              replicas: 0
    metric_backends:
      metrics_storage:
        prometheus:
          endpoint: http://prometheus:9090
          normalize_calls: true
          normalize_duration: true

connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: trace_storage
  prometheus:
    endpoint: 0.0.0.0:8889